import 'dart:math';

class SketchWizardsWordRepository {
  static final List<String> labels = [
    "snail",
    "floor lamp",
    "horse",
    "person walking",
    "hamburger",
    "feather",
    "fire hydrant",
    "ant",
    "axe",
    "screwdriver",
    "socks",
    "tractor",
    "piano",
    "toothbrush",
    "head",
    "book",
    "loudspeaker",
    "standing bird",
    "bicycle",
    "ice-cream-cone",
    "dragon",
    "laptop",
    "zebra",
    "pizza",
    "wheelbarrow",
    "donut",
    "vase",
    "violin",
    "teddy-bear",
    "toilet",
    "church",
    "pear",
    "wineglass",
    "speed-boat",
    "snowboar",
    "lighter",
    "banana",
    "bathtub",
    "squirrel",
    "snowman",
    "penguin",
    "shark",
    "duck",
    "tooth",
    "cabinet",
    "snowboard",
    "helmet",
    "person sitting",
    "envelope",
    "binoculars",
    "mug",
    "human-skeleton",
    "tiger",
    "wheel",
    "fish",
    "stapler",
    "telephone",
    "elephant",
    "baseball bat",
    "teapot",
    "eye",
    "syringe",
    "basket",
    "cloud",
    "armchair",
    "helicopter",
    "hot air balloon",
    "rainbow",
    "walkie talkie",
    "brain",
    "calculator",
    "canoe",
    "windmill",
    "mouse (animal)",
    "purse",
    "crocodile",
    "bus",
    "bridge",
    "cell phone",
    "ladder",
    "saxophone",
    "frog",
    "train",
    "tennis-racket",
    "dog",
    "bread",
    "potted plant",
    "bell",
    "computer-mouse",
    "alarm clock",
    "bottle opener",
    "mailbox",
    "bookshelf",
    "teacup",
    "trumpet",
    "revolver",
    "rollerblades",
    "submarine",
    "apple"
  ];

  static String? _latestLabel;

  static String getRandomLabel() {
    String newLabel = labels[Random().nextInt(labels.length)];

    if (newLabel == _latestLabel) {
      return getRandomLabel();
    }

    return newLabel;
  }
}
